@startuml View Recommendations Activity Diagram
title View Recommendations Activity Diagram

start

:Visit Recommendations Page;

:Retrieve matched recommendations;

if (At least one listing to show?) then (yes)

    while (More recommendations to show?)
        :Display job details;
        
        if ("Swipe Right/Apply Clicked") then (yes)
            :Save application to ApplicationsDB;
            :Display confirmation;
        endif

    endwhile

else
    :Display "No more recommendations to show";
endif

stop

@enduml
