@startuml Job Seeker Profile Match State Transition Diagram
title Job Seeker Application State Transition Diagram

state Idle {
    [*] --> JobPosted
    JobPosted : New job is posted
    JobPosted --> MatchingProfiles : Start matching profiles
}

state MatchingProfiles {
    [*] --> NoMatch
    [*] --> MatchFound
    NoMatch : No matching profiles found
    MatchFound : Matching profiles found
    MatchFound --> NotifyJobSeekers : Notify job seekers
}

state NotifyJobSeekers {
    NotifyJobSeekers : Notification sent to job seekers
}
MatchingProfiles --> [*]

@enduml
